server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: SKCC18D00115.localdomain:9092
      bindings:
        input:
          group: product
          destination: shop
          contentType: application/json
        output:
          destination: shop
          contentType: application/json
---
server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
      bindings:
        input:
          group: product
          destination: shop
          contentType: application/json
        output:
          destination: shop
          contentType: application/json